import os
import uuid
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORTS_DIR = os.path.join(BASE_DIR, "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def create_report(data: Dict[str, Any]) -> str:
    """
    Generate an isolated, collision-free PDF evaluation report for a candidate resume.
    Returns the absolute path to the generated PDF.
    """
    report_uuid = uuid.uuid4().hex[:12]
    filename = f"AI_Resume_Report_{report_uuid}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)

    pdf = canvas.Canvas(file_path, pagesize=letter)
    pdf.setTitle("AI Resume Evaluation Report")

    # Header decoration
    pdf.setFillColor(colors.HexColor("#1e1b4b"))
    pdf.rect(0, 740, 612, 60, fill=True, stroke=False)
    
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(40, 760, "AI Resume Screening & Evaluation Report")

    y = 710

    # Candidate & Role Summary Section
    pdf.setFillColor(colors.HexColor("#0f172a"))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(40, y, "Candidate Evaluation Summary")
    y -= 25

    pdf.setFont("Helvetica", 11)
    score_val = data.get("resume_score", 0.0)
    role_val = data.get("predicted_role", "Unclassified")
    filename_val = data.get("filename", "Uploaded Resume")

    pdf.drawString(50, y, f"Document Name: {filename_val}")
    y -= 20
    pdf.drawString(50, y, f"Predicted Career Category: {role_val}")
    y -= 20
    pdf.drawString(50, y, f"ATS Resume Score: {score_val}%")
    y -= 30

    # Technical Skills Section
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(40, y, "Detected Technical Competencies")
    y -= 22

    pdf.setFont("Helvetica", 10)
    skills = data.get("skills", [])
    if skills:
        skills_str = ", ".join(skills)
        # Wrap skills text into lines
        words = skills_str.split(", ")
        current_line = []
        for word in words:
            current_line.append(word)
            if len(", ".join(current_line)) > 75:
                pdf.drawString(50, y, "• " + ", ".join(current_line))
                y -= 16
                current_line = []
                if y < 60:
                    pdf.showPage()
                    y = 740
        if current_line:
            pdf.drawString(50, y, "• " + ", ".join(current_line))
            y -= 25
    else:
        pdf.drawString(50, y, "No standardized technical keywords detected.")
        y -= 25

    if y < 140:
        pdf.showPage()
        y = 740

    # Job Recommendations Section
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(40, y, "Aligned Career Opportunities & Benchmarks")
    y -= 22

    pdf.setFont("Helvetica", 10)
    recommendations = data.get("recommendations", [])
    if recommendations:
        for rec in recommendations:
            if y < 60:
                pdf.showPage()
                y = 740
            job_name = rec.get("job", "Role")
            match_pct = rec.get("match", 0)
            missing = rec.get("missing_skills", [])
            gap_text = f" (Skill gaps: {', '.join(missing[:3])})" if missing else ""
            pdf.drawString(50, y, f"#{rec.get('rank', 1)} {job_name} — {match_pct}% Match{gap_text}")
            y -= 18
    else:
        pdf.drawString(50, y, "No role recommendations generated.")
        y -= 20

    # Footer
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.setFillColor(colors.HexColor("#64748b"))
    pdf.drawString(40, 30, f"Generated by Smart Analytics Hub AI Engine • Report ID: {report_uuid}")

    pdf.save()
    return file_path